#!/bin/bash
# Nicholas Ferreira - github.com/Nickguitar
# 08/10/21

if [ -z "$(ls -A config_files)" ]; then
	echo "[-] The folder 'config_files' is empty. Put your openvpn.conf files there and try again."
	exit
fi

if [ -z $1 ]; then
	echo "[-] Usage: $0 <openvpn_file.conf> [port (default:3128)]"
	exit
fi

port=3128
if [ ! -z $2 ]; then
	if [[ ! "$2" =~ ^[0-9]+$  ]]; then
		echo "[-] The port must be numerical."
		exit
	fi
	port=$2
fi;

sudo docker build \
--build-arg CONFIG_FILE="`basename $1`" \
-t squid_openvpn:1.0 .

sudo docker run \
-dit \
--cap-add=NET_ADMIN \
--device /dev/net/tun \
--sysctl net.ipv6.conf.all.disable_ipv6=0 \
-p $port:3128 \
squid_openvpn:1.0