#!/bin/bash
if [[ ! $TOR_CONTAINER ]]; then
    /usr/sbin/sshd
    ssh-keyscan -H 127.0.0.1 >> /root/.ssh/known_hosts
    while [[ $(ip -f inet addr show tun0 2>/dev/null| wc -l) == 0 ]]; do true;done
    gw=$(ip route | awk '/default/ {print $3}')
    ip route add to 10.0.0.0/8 via $gw dev eth0
    ip route add to 172.16.0.0/12 via $gw dev eth0
    ip route add to 192.168.0.0/16 via $gw dev eth0
    ssh -N 127.0.0.1 -D 0.0.0.0:9050 -i /root/.ssh/sshkey

fi
