#!/bin/bash
if [[ $TOR_CONTAINER != "yes" ]]; then
    export TEMP_DIR="$(mktemp -d)"
    while [[ $(ip -f inet addr show tun0 2>/dev/null| wc -l) == 0 ]]; do true;done
    export env VPN_IP="$(ip -f inet addr show tun0 | sed -En -e 's/.*inet ([0-9.]+).*/\1/p')"
    envsubst </app/squid/squid.conf >"${TEMP_DIR}/config"
    squid -f "${TEMP_DIR}/config"
    if [ -z ${LAN} ]; then
        gw=$(ip route | awk '/default/ {print $3}')
        ip route add to ${LAN} via $gw dev eth0
    fi
fi

